# Project
 
 Password-Locker

## Author 

 Steve Mwanza

## Description
This is a python application that is used through the terminal. The application takes in user's password for various accounts and stores them. The user has to log in to access the kept details for various accounts created by them.The app has been build to also generate random passwords for users.

## Behaviour Driven Development(BDD)
| Behavior  |      Input       |  Output
|-------------|----------------|---------------|
|Run python3.6 on terminal|The users input their name, email and password to sign in.| Users are given options to sign in, login or exit the application
|---------------|----------------|----------------|
|               | Users create one account or multiple accounts for various  of passwords| Users receive options to create more accounts or exit app|
|------------------|--------------|------------------|
|                |Users can choose to login using their email addresses and passwords| Their accounts are displayed|
|----------------|------------------|------------------|
|                |Users have the option to create new accounts using random passwords| The application generates passwords|

* the user can request the app to generate a password for him/her.
* The user can dispalay the accounts stored with their cridentials.
* Random generated passwords	Passwords generated by the application.
* User accounts with their credentials	Stored user accounts and their passwords




### Prior Installations :

* python3.6
* pip
* pyperclip

#### Cloning 

* git clone  https://github.com/Steve-design/Password-Locker on terminal.
* Navigate to Password-Locker
* Open the project using your suitable text editor.

#### Running the application

* To run the app, use python3 app.py
* To run tests, use python3 -m unittest

### Technologies Used
* Python3.6


### Support

* Steve Mwanza (LinkedIn)
* smzalendo31@gmail.com

### License
This project is licensed under the MIT Open Source license Copyright © 2019. 